"""delivery jobs

Revision ID: 19d5bb6bc596
Revises: 0004_routes
Create Date: 2026-09-25 20:07:41.487697
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = "19d5bb6bc596"
down_revision: str | None = "0004_routes"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "delivery_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("route_id", sa.Integer(), nullable=True),
        sa.Column("source_chat_id", sa.Integer(), nullable=False),
        sa.Column("source_message_id", sa.BigInteger(), nullable=False),
        sa.Column("source_message_ids", sa.Text(), nullable=True),
        sa.Column("media_group_id", sa.BigInteger(), nullable=True),
        sa.Column("target_chat_id", sa.Integer(), nullable=False),
        sa.Column("target_message_id", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ad_applied", sa.Boolean(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["routes.id"],
            name=op.f("fk_delivery_jobs_route_id_routes"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delivery_jobs")),
        sa.UniqueConstraint(
            "source_chat_id",
            "source_message_id",
            "target_chat_id",
            name="uq_delivery_source_message_target",
        ),
    )
    with op.batch_alter_table("delivery_jobs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_delivery_jobs_media_group_id"), ["media_group_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_delivery_jobs_route_id"), ["route_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_delivery_jobs_source_chat_id"), ["source_chat_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_delivery_jobs_source_message_id"), ["source_message_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_delivery_jobs_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_delivery_jobs_target_chat_id"), ["target_chat_id"], unique=False
        )
        batch_op.create_index(
            "ix_delivery_status_next_retry", ["status", "next_retry_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("delivery_jobs", schema=None) as batch_op:
        batch_op.drop_index("ix_delivery_status_next_retry")
        batch_op.drop_index(batch_op.f("ix_delivery_jobs_target_chat_id"))
        batch_op.drop_index(batch_op.f("ix_delivery_jobs_status"))
        batch_op.drop_index(batch_op.f("ix_delivery_jobs_source_message_id"))
        batch_op.drop_index(batch_op.f("ix_delivery_jobs_source_chat_id"))
        batch_op.drop_index(batch_op.f("ix_delivery_jobs_route_id"))
        batch_op.drop_index(batch_op.f("ix_delivery_jobs_media_group_id"))

    op.drop_table("delivery_jobs")
    # ### end Alembic commands ###
